### ISSUE TITLE
bird eye view image formation

### ISSUE THREAD

**Issue by sandeshchand87** [mzki/homography-camera-displacement#2]
i am trying to convert the image formed by fish eye camera into its bird eye view . i am using the intrinsic and extrinsic parametres and following your code but am not getting the perfect bird eye view.the image is moved toeards right in the bird eye view image.

**Comment by mzki** [comment]
If you followed the code in the cells [13] and [14] then it is intended result, since the position of the bird eye view camera is intentionally moved towards right.

> t2 = R2 @ (np.array([0, -2.000, 0]) + _np.array([1.0, 0.0, 1.0])).reshape((3, 1))_

**Comment by mzki** [comment]
No additional questions. Closed
