### ISSUE TITLE
plane normal vector

### ISSUE THREAD

**Issue by nesi73** [mzki/homography-camera-displacement#3]
Hi,

I don't understand how you select the plane normal with this: [0,1,0]  instead of [0,0,1] like in the OpenCV example.

# Plane normal vector at camera 1 coordinate. here, object axis -> camera frame.
n = np.array([0, 1, 0]).reshape((3, 1))

Thank you

**Comment by mzki** [comment]
Hi, 

My example assumes the XZ-plane of the object coordinates is parallel to the plane, which is align to the ground. So the plane normal vector of my example is [0,1,0]  (note that the sign of normal vector is inverted to align the OpenCV example ). In contrast, It seems the OpenCV example assumes the XZ-plane of the object coordinates is orthogonal to the plane. So the plane normal vector of the OpenCV example is [0,0,1], (see solvePnP result of the chessboard in the OpenCV example).

**Comment by mzki** [comment]
answered and closed.
